### ISSUE TITLE
PGUSER is invalid - postgres

### ISSUE THREAD

**Issue by jcoffin** [mckenfra/postgresql-mac-preferences#9]
Fresh install of PostgreSQL v9.4.4, all default settings. I get "The PostgreSQL Server instance is Unknown" with error `PGUSER is invalid - postgres`. The `postgres` user seems to be setup properly and the server is running fine. Any ideas?

**Comment by mckenfra** [comment]
Yes, I've just tested this, having also installed PostgreSQL from http://www.enterprisedb.com

The Postgre Prefs tool runs this command to check if the user exists:

    id -u -n postgres

This works fine if I run it at the command line. But if I run this:

    sudo id -u -n postgres

Then I get this error message:

    "root" execution of the PostgreSQL server is not permitted.
    The server must be started under an unprivileged user ID to prevent
    possible system security compromise.  See the documentation for
    more information on how to properly start the server.

Unfortunately, if you chose the option to install Postgre Prefs for all users, then it runs the above command with the `sudo` in front of it.

So the fix will require modifying the script so that it doesn't ever use `sudo` for this command. Easy enough to do in principle, but I'm just now in the middle of working on a new version of this tool, with lots of modified files. So to make the necessary change, I'm going to have to do a git-branch off the previously-released version - not something I've needed to do before, so could be tricky!

In the meantime, can you try uninstalling the tool (right-click on the icon, and click Remove), then reinstalling but choosing "for this user only". Does that fix it?

**Comment by jcoffin** [comment]
Thanks for the help. I just uninstalled using your instructions on the README. Then I installed using the "this user only" option. But I still have the same error message.

**Comment by mckenfra** [comment]
Yes, I checked the code. It doesn't explicitly put "sudo" in front of the command. But the script is always running as root, regardless of how the preference pane is installed. So I'll need to get it to switch user to a non-root user in order to run that `id -u -n postgres` command without generating that error message.

I'll try to work out the git branching stuff and do a patch release, once I've checked in the stuff I'm working on at the moment.

**Comment by mckenfra** [comment]
Please could you try the latest release, v1.4.1?

Download the latest release at: https://github.com/mckenfra/postgresql-mac-preferences/releases

Let me know if that's working now.

**Comment by jcoffin** [comment]
That worked! Thanks, it also works with v2.0. Great work!

**Comment by mckenfra** [comment]
Cool, I'll close the issue, thanks for raising it!

FYI - hopefully should have a v2.1 out soon. Main improvement is that it will show already-running PostgreSQL servers that weren't configured using the preferences. You will then be able to start/stop these other servers in the same way as the ones you manually added to the preferences.
